/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol/ogrt.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ogrt.pb-c.h"
void   ogrt__job_start__init
                     (OGRT__JobStart         *message)
{
  static const OGRT__JobStart init_value = OGRT__JOB_START__INIT;
  *message = init_value;
}
size_t ogrt__job_start__get_packed_size
                     (const OGRT__JobStart *message)
{
  assert(message->base.descriptor == &ogrt__job_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__job_start__pack
                     (const OGRT__JobStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__job_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__job_start__pack_to_buffer
                     (const OGRT__JobStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__job_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__JobStart *
       ogrt__job_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__JobStart *)
     protobuf_c_message_unpack (&ogrt__job_start__descriptor,
                                allocator, len, data);
}
void   ogrt__job_start__free_unpacked
                     (OGRT__JobStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__job_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__job_end__init
                     (OGRT__JobEnd         *message)
{
  static const OGRT__JobEnd init_value = OGRT__JOB_END__INIT;
  *message = init_value;
}
size_t ogrt__job_end__get_packed_size
                     (const OGRT__JobEnd *message)
{
  assert(message->base.descriptor == &ogrt__job_end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__job_end__pack
                     (const OGRT__JobEnd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__job_end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__job_end__pack_to_buffer
                     (const OGRT__JobEnd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__job_end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__JobEnd *
       ogrt__job_end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__JobEnd *)
     protobuf_c_message_unpack (&ogrt__job_end__descriptor,
                                allocator, len, data);
}
void   ogrt__job_end__free_unpacked
                     (OGRT__JobEnd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__job_end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__shared_object__init
                     (OGRT__SharedObject         *message)
{
  static const OGRT__SharedObject init_value = OGRT__SHARED_OBJECT__INIT;
  *message = init_value;
}
size_t ogrt__shared_object__get_packed_size
                     (const OGRT__SharedObject *message)
{
  assert(message->base.descriptor == &ogrt__shared_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__shared_object__pack
                     (const OGRT__SharedObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__shared_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__shared_object__pack_to_buffer
                     (const OGRT__SharedObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__shared_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__SharedObject *
       ogrt__shared_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__SharedObject *)
     protobuf_c_message_unpack (&ogrt__shared_object__descriptor,
                                allocator, len, data);
}
void   ogrt__shared_object__free_unpacked
                     (OGRT__SharedObject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__shared_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__module__init
                     (OGRT__Module         *message)
{
  static const OGRT__Module init_value = OGRT__MODULE__INIT;
  *message = init_value;
}
size_t ogrt__module__get_packed_size
                     (const OGRT__Module *message)
{
  assert(message->base.descriptor == &ogrt__module__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__module__pack
                     (const OGRT__Module *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__module__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__module__pack_to_buffer
                     (const OGRT__Module *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__module__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__Module *
       ogrt__module__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__Module *)
     protobuf_c_message_unpack (&ogrt__module__descriptor,
                                allocator, len, data);
}
void   ogrt__module__free_unpacked
                     (OGRT__Module *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__module__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__process_info__init
                     (OGRT__ProcessInfo         *message)
{
  static const OGRT__ProcessInfo init_value = OGRT__PROCESS_INFO__INIT;
  *message = init_value;
}
size_t ogrt__process_info__get_packed_size
                     (const OGRT__ProcessInfo *message)
{
  assert(message->base.descriptor == &ogrt__process_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__process_info__pack
                     (const OGRT__ProcessInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__process_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__process_info__pack_to_buffer
                     (const OGRT__ProcessInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__process_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__ProcessInfo *
       ogrt__process_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__ProcessInfo *)
     protobuf_c_message_unpack (&ogrt__process_info__descriptor,
                                allocator, len, data);
}
void   ogrt__process_info__free_unpacked
                     (OGRT__ProcessInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__process_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__process_resource_info__init
                     (OGRT__ProcessResourceInfo         *message)
{
  static const OGRT__ProcessResourceInfo init_value = OGRT__PROCESS_RESOURCE_INFO__INIT;
  *message = init_value;
}
size_t ogrt__process_resource_info__get_packed_size
                     (const OGRT__ProcessResourceInfo *message)
{
  assert(message->base.descriptor == &ogrt__process_resource_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__process_resource_info__pack
                     (const OGRT__ProcessResourceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__process_resource_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__process_resource_info__pack_to_buffer
                     (const OGRT__ProcessResourceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__process_resource_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__ProcessResourceInfo *
       ogrt__process_resource_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__ProcessResourceInfo *)
     protobuf_c_message_unpack (&ogrt__process_resource_info__descriptor,
                                allocator, len, data);
}
void   ogrt__process_resource_info__free_unpacked
                     (OGRT__ProcessResourceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__process_resource_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ogrt__job_info__init
                     (OGRT__JobInfo         *message)
{
  static const OGRT__JobInfo init_value = OGRT__JOB_INFO__INIT;
  *message = init_value;
}
size_t ogrt__job_info__get_packed_size
                     (const OGRT__JobInfo *message)
{
  assert(message->base.descriptor == &ogrt__job_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ogrt__job_info__pack
                     (const OGRT__JobInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ogrt__job_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ogrt__job_info__pack_to_buffer
                     (const OGRT__JobInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ogrt__job_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OGRT__JobInfo *
       ogrt__job_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OGRT__JobInfo *)
     protobuf_c_message_unpack (&ogrt__job_info__descriptor,
                                allocator, len, data);
}
void   ogrt__job_info__free_unpacked
                     (OGRT__JobInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ogrt__job_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ogrt__job_start__field_descriptors[2] =
{
  {
    "job_id",
    100,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__JobStart, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    101,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__JobStart, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__job_start__field_indices_by_name[] = {
  0,   /* field[0] = job_id */
  1,   /* field[1] = start_time */
};
static const ProtobufCIntRange ogrt__job_start__number_ranges[1 + 1] =
{
  { 100, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ogrt__job_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.JobStart",
  "JobStart",
  "OGRT__JobStart",
  "OGRT",
  sizeof(OGRT__JobStart),
  2,
  ogrt__job_start__field_descriptors,
  ogrt__job_start__field_indices_by_name,
  1,  ogrt__job_start__number_ranges,
  (ProtobufCMessageInit) ogrt__job_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__job_end__field_descriptors[2] =
{
  {
    "job_id",
    200,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__JobEnd, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    201,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__JobEnd, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__job_end__field_indices_by_name[] = {
  1,   /* field[1] = end_time */
  0,   /* field[0] = job_id */
};
static const ProtobufCIntRange ogrt__job_end__number_ranges[1 + 1] =
{
  { 200, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ogrt__job_end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.JobEnd",
  "JobEnd",
  "OGRT__JobEnd",
  "OGRT",
  sizeof(OGRT__JobEnd),
  2,
  ogrt__job_end__field_descriptors,
  ogrt__job_end__field_indices_by_name,
  1,  ogrt__job_end__number_ranges,
  (ProtobufCMessageInit) ogrt__job_end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__shared_object__field_descriptors[2] =
{
  {
    "path",
    400,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__SharedObject, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    401,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__SharedObject, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__shared_object__field_indices_by_name[] = {
  0,   /* field[0] = path */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange ogrt__shared_object__number_ranges[1 + 1] =
{
  { 400, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ogrt__shared_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.SharedObject",
  "SharedObject",
  "OGRT__SharedObject",
  "OGRT",
  sizeof(OGRT__SharedObject),
  2,
  ogrt__shared_object__field_descriptors,
  ogrt__shared_object__field_indices_by_name,
  1,  ogrt__shared_object__number_ranges,
  (ProtobufCMessageInit) ogrt__shared_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__module__field_descriptors[1] =
{
  {
    "name",
    700,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__Module, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__module__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange ogrt__module__number_ranges[1 + 1] =
{
  { 700, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ogrt__module__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.Module",
  "Module",
  "OGRT__Module",
  "OGRT",
  sizeof(OGRT__Module),
  1,
  ogrt__module__field_descriptors,
  ogrt__module__field_indices_by_name,
  1,  ogrt__module__number_ranges,
  (ProtobufCMessageInit) ogrt__module__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__process_info__field_descriptors[15] =
{
  {
    "uuid",
    299,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "binpath",
    300,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, binpath),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    301,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_pid",
    302,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, parent_pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    303,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    304,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    305,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    306,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    307,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmdline",
    308,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, cmdline),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_variables",
    309,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OGRT__ProcessInfo, n_environment_variables),
    offsetof(OGRT__ProcessInfo, environment_variables),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arguments",
    310,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OGRT__ProcessInfo, n_arguments),
    offsetof(OGRT__ProcessInfo, arguments),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shared_objects",
    311,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OGRT__ProcessInfo, n_shared_objects),
    offsetof(OGRT__ProcessInfo, shared_objects),
    &ogrt__shared_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loaded_modules",
    312,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OGRT__ProcessInfo, n_loaded_modules),
    offsetof(OGRT__ProcessInfo, loaded_modules),
    &ogrt__module__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cwd",
    313,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessInfo, cwd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__process_info__field_indices_by_name[] = {
  11,   /* field[11] = arguments */
  1,   /* field[1] = binpath */
  9,   /* field[9] = cmdline */
  14,   /* field[14] = cwd */
  10,   /* field[10] = environment_variables */
  8,   /* field[8] = hostname */
  6,   /* field[6] = job_id */
  13,   /* field[13] = loaded_modules */
  3,   /* field[3] = parent_pid */
  2,   /* field[2] = pid */
  12,   /* field[12] = shared_objects */
  5,   /* field[5] = signature */
  4,   /* field[4] = time */
  7,   /* field[7] = username */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange ogrt__process_info__number_ranges[1 + 1] =
{
  { 299, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor ogrt__process_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.ProcessInfo",
  "ProcessInfo",
  "OGRT__ProcessInfo",
  "OGRT",
  sizeof(OGRT__ProcessInfo),
  15,
  ogrt__process_info__field_descriptors,
  ogrt__process_info__field_indices_by_name,
  1,  ogrt__process_info__number_ranges,
  (ProtobufCMessageInit) ogrt__process_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__process_resource_info__field_descriptors[11] =
{
  {
    "uuid",
    99,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    104,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_utime",
    105,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_utime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_stime",
    106,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_stime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_maxrss",
    107,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_maxrss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_minflt",
    108,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_minflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_majflt",
    109,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_majflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_inblock",
    110,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_inblock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_oublock",
    111,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_oublock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nvcsw",
    112,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_nvcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nivcsw",
    113,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OGRT__ProcessResourceInfo, ru_nivcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__process_resource_info__field_indices_by_name[] = {
  7,   /* field[7] = ru_inblock */
  6,   /* field[6] = ru_majflt */
  4,   /* field[4] = ru_maxrss */
  5,   /* field[5] = ru_minflt */
  10,   /* field[10] = ru_nivcsw */
  9,   /* field[9] = ru_nvcsw */
  8,   /* field[8] = ru_oublock */
  3,   /* field[3] = ru_stime */
  2,   /* field[2] = ru_utime */
  1,   /* field[1] = time */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange ogrt__process_resource_info__number_ranges[2 + 1] =
{
  { 99, 0 },
  { 104, 1 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ogrt__process_resource_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.ProcessResourceInfo",
  "ProcessResourceInfo",
  "OGRT__ProcessResourceInfo",
  "OGRT",
  sizeof(OGRT__ProcessResourceInfo),
  11,
  ogrt__process_resource_info__field_descriptors,
  ogrt__process_resource_info__field_indices_by_name,
  2,  ogrt__process_resource_info__number_ranges,
  (ProtobufCMessageInit) ogrt__process_resource_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ogrt__job_info__field_descriptors[2] =
{
  {
    "job_id",
    400,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OGRT__JobInfo, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processes",
    401,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OGRT__JobInfo, n_processes),
    offsetof(OGRT__JobInfo, processes),
    &ogrt__process_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ogrt__job_info__field_indices_by_name[] = {
  0,   /* field[0] = job_id */
  1,   /* field[1] = processes */
};
static const ProtobufCIntRange ogrt__job_info__number_ranges[1 + 1] =
{
  { 400, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ogrt__job_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OGRT.JobInfo",
  "JobInfo",
  "OGRT__JobInfo",
  "OGRT",
  sizeof(OGRT__JobInfo),
  2,
  ogrt__job_info__field_descriptors,
  ogrt__job_info__field_indices_by_name,
  1,  ogrt__job_info__number_ranges,
  (ProtobufCMessageInit) ogrt__job_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ogrt__message_type__enum_values_by_number[7] =
{
  { "JobStartMsg", "OGRT__MESSAGE_TYPE__JobStartMsg", 0 },
  { "JobEndMsg", "OGRT__MESSAGE_TYPE__JobEndMsg", 11 },
  { "ProcessInfoMsg", "OGRT__MESSAGE_TYPE__ProcessInfoMsg", 12 },
  { "SharedObjectMsg", "OGRT__MESSAGE_TYPE__SharedObjectMsg", 13 },
  { "ForkMsg", "OGRT__MESSAGE_TYPE__ForkMsg", 14 },
  { "ExecveMsg", "OGRT__MESSAGE_TYPE__ExecveMsg", 15 },
  { "ProcessResourceMsg", "OGRT__MESSAGE_TYPE__ProcessResourceMsg", 16 },
};
static const ProtobufCIntRange ogrt__message_type__value_ranges[] = {
{0, 0},{11, 1},{0, 7}
};
static const ProtobufCEnumValueIndex ogrt__message_type__enum_values_by_name[7] =
{
  { "ExecveMsg", 5 },
  { "ForkMsg", 4 },
  { "JobEndMsg", 1 },
  { "JobStartMsg", 0 },
  { "ProcessInfoMsg", 2 },
  { "ProcessResourceMsg", 6 },
  { "SharedObjectMsg", 3 },
};
const ProtobufCEnumDescriptor ogrt__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OGRT.MessageType",
  "MessageType",
  "OGRT__MessageType",
  "OGRT",
  7,
  ogrt__message_type__enum_values_by_number,
  7,
  ogrt__message_type__enum_values_by_name,
  2,
  ogrt__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
