/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol/ogrt.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ogrt.pb-c.h"
void   msg__shared_object__init
                     (Msg__SharedObject         *message)
{
  static const Msg__SharedObject init_value = MSG__SHARED_OBJECT__INIT;
  *message = init_value;
}
size_t msg__shared_object__get_packed_size
                     (const Msg__SharedObject *message)
{
  assert(message->base.descriptor == &msg__shared_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__shared_object__pack
                     (const Msg__SharedObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__shared_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__shared_object__pack_to_buffer
                     (const Msg__SharedObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__shared_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__SharedObject *
       msg__shared_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__SharedObject *)
     protobuf_c_message_unpack (&msg__shared_object__descriptor,
                                allocator, len, data);
}
void   msg__shared_object__free_unpacked
                     (Msg__SharedObject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__shared_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__module__init
                     (Msg__Module         *message)
{
  static const Msg__Module init_value = MSG__MODULE__INIT;
  *message = init_value;
}
size_t msg__module__get_packed_size
                     (const Msg__Module *message)
{
  assert(message->base.descriptor == &msg__module__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__module__pack
                     (const Msg__Module *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__module__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__module__pack_to_buffer
                     (const Msg__Module *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__module__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__Module *
       msg__module__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__Module *)
     protobuf_c_message_unpack (&msg__module__descriptor,
                                allocator, len, data);
}
void   msg__module__free_unpacked
                     (Msg__Module *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__module__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__process_start__init
                     (Msg__ProcessStart         *message)
{
  static const Msg__ProcessStart init_value = MSG__PROCESS_START__INIT;
  *message = init_value;
}
size_t msg__process_start__get_packed_size
                     (const Msg__ProcessStart *message)
{
  assert(message->base.descriptor == &msg__process_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__process_start__pack
                     (const Msg__ProcessStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__process_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__process_start__pack_to_buffer
                     (const Msg__ProcessStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__process_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__ProcessStart *
       msg__process_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__ProcessStart *)
     protobuf_c_message_unpack (&msg__process_start__descriptor,
                                allocator, len, data);
}
void   msg__process_start__free_unpacked
                     (Msg__ProcessStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__process_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__process_end__init
                     (Msg__ProcessEnd         *message)
{
  static const Msg__ProcessEnd init_value = MSG__PROCESS_END__INIT;
  *message = init_value;
}
size_t msg__process_end__get_packed_size
                     (const Msg__ProcessEnd *message)
{
  assert(message->base.descriptor == &msg__process_end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__process_end__pack
                     (const Msg__ProcessEnd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__process_end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__process_end__pack_to_buffer
                     (const Msg__ProcessEnd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__process_end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__ProcessEnd *
       msg__process_end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__ProcessEnd *)
     protobuf_c_message_unpack (&msg__process_end__descriptor,
                                allocator, len, data);
}
void   msg__process_end__free_unpacked
                     (Msg__ProcessEnd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__process_end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg__process_info__init
                     (Msg__ProcessInfo         *message)
{
  static const Msg__ProcessInfo init_value = MSG__PROCESS_INFO__INIT;
  *message = init_value;
}
size_t msg__process_info__get_packed_size
                     (const Msg__ProcessInfo *message)
{
  assert(message->base.descriptor == &msg__process_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__process_info__pack
                     (const Msg__ProcessInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__process_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__process_info__pack_to_buffer
                     (const Msg__ProcessInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__process_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg__ProcessInfo *
       msg__process_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg__ProcessInfo *)
     protobuf_c_message_unpack (&msg__process_info__descriptor,
                                allocator, len, data);
}
void   msg__process_info__free_unpacked
                     (Msg__ProcessInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__process_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg__shared_object__field_descriptors[2] =
{
  {
    "path",
    400,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__SharedObject, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    401,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__SharedObject, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__shared_object__field_indices_by_name[] = {
  0,   /* field[0] = path */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange msg__shared_object__number_ranges[1 + 1] =
{
  { 400, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg__shared_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.SharedObject",
  "SharedObject",
  "Msg__SharedObject",
  "msg",
  sizeof(Msg__SharedObject),
  2,
  msg__shared_object__field_descriptors,
  msg__shared_object__field_indices_by_name,
  1,  msg__shared_object__number_ranges,
  (ProtobufCMessageInit) msg__shared_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__module__field_descriptors[1] =
{
  {
    "name",
    700,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__Module, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__module__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange msg__module__number_ranges[1 + 1] =
{
  { 700, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg__module__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.Module",
  "Module",
  "Msg__Module",
  "msg",
  sizeof(Msg__Module),
  1,
  msg__module__field_descriptors,
  msg__module__field_indices_by_name,
  1,  msg__module__number_ranges,
  (ProtobufCMessageInit) msg__module__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__process_start__field_descriptors[15] =
{
  {
    "uuid",
    299,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "binpath",
    300,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, binpath),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    301,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_pid",
    302,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, parent_pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    303,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    304,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    305,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    306,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    307,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmdline",
    308,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, cmdline),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_variables",
    309,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Msg__ProcessStart, n_environment_variables),
    offsetof(Msg__ProcessStart, environment_variables),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arguments",
    310,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Msg__ProcessStart, n_arguments),
    offsetof(Msg__ProcessStart, arguments),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shared_objects",
    311,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__ProcessStart, n_shared_objects),
    offsetof(Msg__ProcessStart, shared_objects),
    &msg__shared_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loaded_modules",
    312,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__ProcessStart, n_loaded_modules),
    offsetof(Msg__ProcessStart, loaded_modules),
    &msg__module__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cwd",
    313,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessStart, cwd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__process_start__field_indices_by_name[] = {
  11,   /* field[11] = arguments */
  1,   /* field[1] = binpath */
  9,   /* field[9] = cmdline */
  14,   /* field[14] = cwd */
  10,   /* field[10] = environment_variables */
  8,   /* field[8] = hostname */
  6,   /* field[6] = job_id */
  13,   /* field[13] = loaded_modules */
  3,   /* field[3] = parent_pid */
  2,   /* field[2] = pid */
  12,   /* field[12] = shared_objects */
  5,   /* field[5] = signature */
  4,   /* field[4] = time */
  7,   /* field[7] = username */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange msg__process_start__number_ranges[1 + 1] =
{
  { 299, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor msg__process_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.ProcessStart",
  "ProcessStart",
  "Msg__ProcessStart",
  "msg",
  sizeof(Msg__ProcessStart),
  15,
  msg__process_start__field_descriptors,
  msg__process_start__field_indices_by_name,
  1,  msg__process_start__number_ranges,
  (ProtobufCMessageInit) msg__process_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__process_end__field_descriptors[12] =
{
  {
    "uuid",
    99,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    104,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_utime",
    105,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_utime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_stime",
    106,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_stime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_maxrss",
    107,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_maxrss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_minflt",
    108,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_minflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_majflt",
    109,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_majflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_inblock",
    110,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_inblock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_oublock",
    111,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_oublock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nvcsw",
    112,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_nvcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nivcsw",
    113,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, ru_nivcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startTime",
    114,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessEnd, starttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__process_end__field_indices_by_name[] = {
  7,   /* field[7] = ru_inblock */
  6,   /* field[6] = ru_majflt */
  4,   /* field[4] = ru_maxrss */
  5,   /* field[5] = ru_minflt */
  10,   /* field[10] = ru_nivcsw */
  9,   /* field[9] = ru_nvcsw */
  8,   /* field[8] = ru_oublock */
  3,   /* field[3] = ru_stime */
  2,   /* field[2] = ru_utime */
  11,   /* field[11] = startTime */
  1,   /* field[1] = time */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange msg__process_end__number_ranges[2 + 1] =
{
  { 99, 0 },
  { 104, 1 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor msg__process_end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.ProcessEnd",
  "ProcessEnd",
  "Msg__ProcessEnd",
  "msg",
  sizeof(Msg__ProcessEnd),
  12,
  msg__process_end__field_descriptors,
  msg__process_end__field_indices_by_name,
  2,  msg__process_end__number_ranges,
  (ProtobufCMessageInit) msg__process_end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg__process_info__field_descriptors[25] =
{
  {
    "uuid",
    500,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "binpath",
    501,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, binpath),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    502,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_pid",
    503,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, parent_pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    504,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    505,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    506,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    507,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, job_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    508,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    509,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmdline",
    510,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, cmdline),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cwd",
    511,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, cwd),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_variables",
    512,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Msg__ProcessInfo, n_environment_variables),
    offsetof(Msg__ProcessInfo, environment_variables),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arguments",
    513,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Msg__ProcessInfo, n_arguments),
    offsetof(Msg__ProcessInfo, arguments),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shared_objects",
    514,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__ProcessInfo, n_shared_objects),
    offsetof(Msg__ProcessInfo, shared_objects),
    &msg__shared_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loaded_modules",
    515,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Msg__ProcessInfo, n_loaded_modules),
    offsetof(Msg__ProcessInfo, loaded_modules),
    &msg__module__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_utime",
    516,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_utime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_stime",
    517,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_stime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_maxrss",
    518,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_maxrss),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_minflt",
    519,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_minflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_majflt",
    520,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_majflt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_inblock",
    521,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_inblock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_oublock",
    522,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_oublock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nvcsw",
    523,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_nvcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ru_nivcsw",
    524,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Msg__ProcessInfo, ru_nivcsw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__process_info__field_indices_by_name[] = {
  13,   /* field[13] = arguments */
  1,   /* field[1] = binpath */
  10,   /* field[10] = cmdline */
  11,   /* field[11] = cwd */
  5,   /* field[5] = end_time */
  12,   /* field[12] = environment_variables */
  9,   /* field[9] = hostname */
  7,   /* field[7] = job_id */
  15,   /* field[15] = loaded_modules */
  3,   /* field[3] = parent_pid */
  2,   /* field[2] = pid */
  21,   /* field[21] = ru_inblock */
  20,   /* field[20] = ru_majflt */
  18,   /* field[18] = ru_maxrss */
  19,   /* field[19] = ru_minflt */
  24,   /* field[24] = ru_nivcsw */
  23,   /* field[23] = ru_nvcsw */
  22,   /* field[22] = ru_oublock */
  17,   /* field[17] = ru_stime */
  16,   /* field[16] = ru_utime */
  14,   /* field[14] = shared_objects */
  6,   /* field[6] = signature */
  4,   /* field[4] = start_time */
  8,   /* field[8] = username */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange msg__process_info__number_ranges[1 + 1] =
{
  { 500, 0 },
  { 0, 25 }
};
const ProtobufCMessageDescriptor msg__process_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg.ProcessInfo",
  "ProcessInfo",
  "Msg__ProcessInfo",
  "msg",
  sizeof(Msg__ProcessInfo),
  25,
  msg__process_info__field_descriptors,
  msg__process_info__field_indices_by_name,
  1,  msg__process_info__number_ranges,
  (ProtobufCMessageInit) msg__process_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue msg__message_type__enum_values_by_number[3] =
{
  { "UnknownMsg", "MSG__MESSAGE_TYPE__UnknownMsg", 0 },
  { "ProcessStartMsg", "MSG__MESSAGE_TYPE__ProcessStartMsg", 12 },
  { "ProcessEndMsg", "MSG__MESSAGE_TYPE__ProcessEndMsg", 16 },
};
static const ProtobufCIntRange msg__message_type__value_ranges[] = {
{0, 0},{12, 1},{16, 2},{0, 3}
};
static const ProtobufCEnumValueIndex msg__message_type__enum_values_by_name[3] =
{
  { "ProcessEndMsg", 2 },
  { "ProcessStartMsg", 1 },
  { "UnknownMsg", 0 },
};
const ProtobufCEnumDescriptor msg__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "msg.MessageType",
  "MessageType",
  "Msg__MessageType",
  "msg",
  3,
  msg__message_type__enum_values_by_number,
  3,
  msg__message_type__enum_values_by_name,
  3,
  msg__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
