trigger:
- azure-ci

resources:
  containers:
  - container: ogrt-builder
    image: ograth/ogrt-builder:1.0.0
  - container: debian-stable
    image: debian:stable
  - container: centos-7
    image: centos:7
  - container: centos-6
    image: centos:6

jobs:
- job: Build
  strategy:
    matrix:
      Builder:
        containerName: ogrt-builder
        prepareCmd: "echo 'skipping preparation...'"
        vendorCmd: "echo 'skipping vendoring...'"
      Debian-stable:
        containerName: debian-stable
        prepareCmd: "apt-get update && apt-get install -y build-essential pkg-config python wget"
        vendorCmd: "./vendorize"
      CentOS-6:
        containerName: centos-6
        prepareCmd: "yum groupinstall -y 'Development Tools' && yum install -y wget"
        vendorCmd: "./vendorize"
      CentOS-7:
        containerName: centos-7
        prepareCmd: "yum groupinstall -y 'Development Tools' && yum install -y wget"
        vendorCmd: "./vendorize"
  pool:
    vmImage: 'Ubuntu-16.04'
  container: $[ variables['containerName'] ]
  steps:
  - script: |
      echo "running in $(containerName)"
      $(prepareCmd)
      $(vendorCmd)
      ./configure
      make
    displayName: 'build'
    workingDirectory: 'client'
