trigger:
- azure-ci

resources:
  containers:
  - container: ogrt-builder
    image: ograth/ogrt-builder:1.0.0

jobs:
- job: Build
  strategy:
    matrix:
      Config1:
        CONFIG_OPTIONS: 'Config1'
      Config2:
        CONFIG_OPTIONS: 'Config2'
  pool:
    vmImage: 'Ubuntu-16.04'
  container: ogrt-builder
  steps:
  - script: |
      echo $(CONFIG_OPTIONS)
      ./configure
      make
    displayName: 'build'
    workingDirectory: 'client'
