trigger:
- azure-ci

resources:
  containers:
  - container: ogrt-builder
    image: ograth/ogrt-builder:1.0.0
  - container: debian-stable
    image: ograth/debian:stable-essential
  - container: centos-7
    image: ograth/centos:7-devtools
  - container: centos-6
    image: ograth/centos:6-devtools

jobs:
- job: Build
  strategy:
    matrix:
      Builder:
        containerName: ogrt-builder
        vendorCmd: "echo 'skipping vendoring...'"
      Debian-stable:
        containerName: debian-stable
        vendorCmd: "./vendorize"
      CentOS-6:
        containerName: centos-6
        vendorCmd: "./vendorize"
      CentOS-7:
        containerName: centos-7
        vendorCmd: "./vendorize"
  pool:
    vmImage: 'Ubuntu-16.04'
  container: $[ variables['containerName'] ]
  steps:
  - script: |
      echo "running in $(containerName)"
      $(vendorCmd)
      ./configure
      make
    displayName: 'build'
    workingDirectory: 'client'
