trigger:
- azure-ci


jobs:
- job: Build
  strategy:
    matrix:
      Config1:
        CONFIG_OPTIONS: 'Config1'
      Config2:
        CONFIG_OPTIONS: 'Config2'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      ./vendorize
    displayName: 'vendorize'
    workingDirectory: 'client'
  - script: |
      echo $(CONFIG_OPTIONS)
      ./configure
      make
    displayName: 'build'
    workingDirectory: 'client'
